// Code generated by "stringer -type=status"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[todo-0]
	_ = x[doing-1]
	_ = x[done-2]
	_ = x[board-0]
	_ = x[form-1]
}

const _status_name = "tododoingdone"

var _status_index = [...]uint8{0, 4, 9, 13}

func (i status) String() string {
	if i < 0 || i >= status(len(_status_index)-1) {
		return "status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _status_name[_status_index[i]:_status_index[i+1]]
}
